import { Logo, SidebarNav } from '@/components'
import '@/styles/main.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen w-full bg-violet-600 flex'>
        <aside className='flex flex-col pl-9 pr-7 py-8 flex-1 gap-14'>
          <Logo />

          <SidebarNav />
        </aside>
        <div className='mt-1 rounded-tl-3xl bg-zinc-50 px-8 py-12 w-full'>
          {children}
        </div>
      </body>
    </html>
  )
}
